### ISSUE TITLE
Add Object ID to shops when returning "get-prices" endpoint

### ISSUE THREAD

**Issue by bakedog417** [TheKye/EM-Framework#18]
**Is your feature request related to a problem? Please describe.**
Currently, when using the get-prices endpoint, I have to use three fields to determine if a shop is unique.  If we return the object ID with the info, the data can better used in determining if a shop is different from another.

**Describe the solution you'd like**
Return Object ID for shops on get-prices endpoint

**Additional context**

This is a poor attempt at an equals function:
![image](https://user-images.githubusercontent.com/29547245/191796044-4811e8eb-3dc3-41bb-8317-0690ce826330.png)

**Comment by TheKye** [comment]
so basically, you want an attached ID for the shop itself not items in the shop? so you can compare 2 shops of the same ID and if they are the same then just add the info to the same table instead of making a new one kind of thing?

**Comment by bakedog417** [comment]
If I wanted to get really squirrelly, I'd want a list of items per shop entry.  I am having to convert it after I make the call anyways.  Here is how I structure the data once I make the call:
![image](https://user-images.githubusercontent.com/29547245/191806087-d58d99c3-5f41-47b0-889f-1ce840c18c52.png)

But, getting the object ID would be a great start without too much surgery.
