### ISSUE TITLE
ForSale value is wrong when adding Buy Offers to return list

### ISSUE THREAD

**Issue by bakedog417** [TheKye/EM-Framework#19]
These two lines are an error I believe.  ForSale is used to designate if an item is being sold or purchased.  Here you are building up the buy offers and set ForSale to true.

https://github.com/TheKye/EM-Framework/blob/70d67404eda9b15bee1f4d41520689d21a5f0f06/Eco.EM.Framework/Utils/ShopUtils.cs#L175

https://github.com/TheKye/EM-Framework/blob/70d67404eda9b15bee1f4d41520689d21a5f0f06/Eco.EM.Framework/Utils/ShopUtils.cs#L188

**Comment by TheKye** [comment]
hmm they where false :/ ill fix that up
