### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by NextReset** [TheKye/EM-Framework#25]
hi there ,

Users can's use unstuck or any other commands any more do to a EM framwork premission that will not alow them is there something i need to change or is this a bug?

**Comment by TheKye** [comment]
try running `/behaviour-command user, true`

**Comment by NextReset** [comment]
haa yeah that worked i think some how it was on false ... i was already going thru the .cs files  :P

**Comment by TheKye** [comment]
haven't seen this issue come back so closing for now :)
