### ISSUE TITLE
Add Store Coordinates to get-prices API endpoint

### ISSUE THREAD

**Issue by Maistho** [TheKye/EM-Framework#34]
I'm trying to use the price information to help transporters find good transport opportunities, and getting the coordinates of the Store would help with that. 

Would it be possible to add Store coordinates to the API endpoint?

I'm willing to implement this with a PR if it's something you're willing to add :)

**Comment by TheKye** [comment]
absolutely! if you are willing to do a pr for it i would accept it!

**Comment by Maistho** [comment]
Aight, I'll look at implementing it some time this week 👍

**Comment by TheKye** [comment]
https://github.com/TheKye/EM-Framework/blob/staging/Eco.EM.Framework/Utils/ShopUtils.cs

all the information the api returns is collected from here

**Comment by TheKye** [comment]
done :)
