### ISSUE TITLE
Allow overriding of localised recipe names

### ISSUE THREAD

**Issue by Dave247** [TheKye/EM-Framework#37]
I noticed that when editing a modded recipe that is support by the framework that there is a LocalizableName field that isn't editable in the serverUI, where I assume the intent is to be able to override the display name that shows up in a crafting table for the recipe. There are times when you would want change this, such as when making a quick and dirty change to the output of the recipe, such as replacing a skill book with a scroll, and the old name not representing the outputted product.

**Comment by TheKye** [comment]
this was added in EM Framework 3.5.0 and has been released
