### ISSUE TITLE
[Bug] Failed to start the server. Exception was Exception: ReflectionTypeLoadException

### ISSUE THREAD

**Issue by ErythroCraft** [TheKye/EM-Framework#39]
**Describe the bug**
After installing EM-Framework server crashed with error [ReflectionTypeLoadingExeption] on System.Private.CoreLib

**To Reproduce**
1. Installing mod EM-Framework
2. Starting Server
3. Server crash with error

Log file: [log_240106083945.log](https://github.com/TheKye/EM-Framework/files/13848756/log_240106083945.log)

**Server**
 - OS: Windows 11
 - Eco Server Version [10.0.4]
 - EM Framework Version [3.3.2]

Maybe your mod is out of date.

**Comment by TheKye** [comment]
the version of the mod you have is out of date, you can get the latest version in mod.io/g/eco :)

**Comment by TheKye** [comment]
https://mod.io/g/eco/m/elixr-mods-em-framework

latest version is 3.5.1 :)

**Comment by ErythroCraft** [comment]
Yes. I've seen. Can you update your repo [Releases][https://github.com/TheKye/EM-Framework/releases)

I want to follow you if you create updates.

Thanks for your help playing eco better.

**Comment by TheKye** [comment]
yeah I can update the repo releases no worries :)

and thank you for your support :)

**Comment by ErythroCraft** [comment]
Perfect.
